alert("Instrucciones: Debe de tomar un trago cuando usted si hizo lo que le dice el Yo nunca. La aplicacion esta pensada para todo tipo de publico pero esta escrita con el vocabulario usado en Cuba. La aplicacion aun es joven y necesita de su ayuda para crecer. Envie nuevas preguntas al correo rop010698@gmail.com.Un placer ayudarle a pecar. ")
        i = 1;
        
	var textos = [" Yo nunca he vuelto con mi ex.",
" He mandado nudes.",
" He aparentado no  estar borracho para no discutir con mi madre.",
" Yo nunca me he liado con el ex de un amig@",
"  he escrito a mi ex una noche de fiesta",
"  he fingido que me llamaban para escapar de una cita o lugar",
" he estado más de tres días sin ducharme ",
" me he imaginado siendo del sexo opuesto ",
"  he  perdido un movil",
"  mentí en el Yo Nunca",
"  he estornudado y me ha salido un moco",
"  he indicado mal un camino cuando me han preguntado",
"  he olido mi propio pedo",
"  he intentado mover cosas con la mente (sin resultado)",
"  he mirado el papel después de ir al baño",
" he mandado un audio subidito de tono a mi madre por error", 
" he amanecido en un parque borracho", 
"He salido con ropa interior rota", 
"He pasado pena al acostarme con alguien desconocid@", 
"Me fugue de la escuela", 
"Hice fraude", 
"He tratado de entrar al Facebook de alguien", 
"He visto desnud@ por error a alguien", 
"No me he confundido de contacto en WhatSapp y le he dicho algo ofencivo", 
"He visto porno", 
"He sido infiel", 
" He pensado que nadie me quiere", 
"He intentado suicidarme", 
"Nunca he mirado escondido a alguien mientras se cambiaba", 
"He pasado años atras de una persona y no le dije que me gustaba", 
"He hecho un baile sexy para alguien en las redes", 
"He he sentido atraid@ por alguien con quien chateo en las redes", 
"He estado detenido", 
"Me he mojado la punta de los labios para aparentar que estoy tomando porque estoy borracho", 
"He sido estafado", 
"He publicado por equivocacion una foto comprometedora", 
"He dicho que voy a casa de un@ amig@ para escaparme de fiestas", 
"Me he ido sin pagar de un lugar (por equivocacion o a proposito)", 
"He visto a dos amigos mios teniendo sexo", 
"He follado en publico", 
"He usado ropa del sexo opuesto", 
"He ido a salir con un piquete y he regresado con otro", 
"Me he juntado con un piquete que ni conozco solo para emborracharme y pasar la noche", 
"Me he masturbado en una casa agena", 
"He sido asaltad@", 
"Me he tocado el celular despues de tirarme un pedo para aparentar", 
"Me mirado hacia atras despues de tirarme un pedo", 
"He cagado en la calle", 
"Me he acostado con una persona mucho mayor que yo (+ de 20 años)", 
"He visto porno en la escuela",
"Yo nunca he aparentado estar tomando para que no vean que estoy borracho", 
"He sateado con mas de 2 personas a la vez por mensajes", 
"He mentido por amor ", 
"Tuve  una fantasía rara", 
"He traicionado a un amigo para beneficiarme", 
"Me he fijado en alguien que no debo", 
"He tenido un orgasmo", 
"He follado más de 3 veces seguidas ", 
"He estado con más de un@ chic@ en un día", 
"He hecho una orgía", 
"He tenido sexo oral",
"He tenido sexo anal", 
"Le he deseado la muerte alguien", 
"He sentido envidia", 
"Me he alegrado de la desgracia de alguien", 
"He fingido un orgasmo ", 
"He mentido a mi madre", 
"He deseado irme lejos por un tiempo", 
"He tenido ganas de morirme", 
"Me he sentido sol@", 
"He dudado de mi", 
"He fantaseado con alguien mientras converso con esa persona", 
"He desconfiado de mis amistades", 
"He sentido vergüenza de mi cuerpo ", 
"He tenido complejos", 
"Me he enamorado", 
"Me he fijado en otra persona q no sea mi pareja ", 
"Me he sentido atraída por alguien del sexo opuesto", 
"Me he sentido atraída por alguien del mismo sexo", 
"He fingido estar borracho", 
"He dejado tirado a alguien que me necesita", 
"He llegado tarde a una cita", 
"He tenido una experiencia sexual interesante", 
"He follado delante de alguien", 
"He follado con un familiar", 
"Me he enamorado de un familiar", 
"He tenido sexo en la escuela", 
"He sido humillado en publico", 
"Me he caido de la silla", 
"Me he caido en publico", 
"He llorado en publico", 
"Me he exitado pensando en cosas pervertidas en un luagr publico", 
"Le he hecho bromas pesadas a desconocidos", 
"He sentido curiosidad sobre que se siente estar con alguien de tu propio sexo", 
"Me he orinado mientras dormia despues de grande", 
"He visto porno gay", 
"He vendido algo ilegal", 
"Me he drogado", 
"He inventado excusas para no follar", 
"He matado a un familiar en las mentiras a los profesores", 
"Le dije compañera a un compañero sin querer",
"He sido estafado",
"me he excitado en público",
"he tenido sexo borracho",
"he deseado follar con más de una persona a la vez.",
"he pensado que soy mala hoja.",
"he tragado semen ",
"he salido con ropa interior rota.",
"he pensado en cosas hot estando rodeada de personas ", "tenido sexo en la playa.",
"he follado con mas de 1persona un mismo día.",
"he pasado una pena en casa d la familia de mi pareja.",
"he hecho un papelazo borracho.",
"me he sentido atraído por alguien q no debo.",
"he tenido más de tres orgasmos en un día.",
"he tomado para emborracharme y dejar de sentir nervios.",
"me he embrrachado  en un lugar o momento q no debía ",
"he follado borracho",
"me he masturbado mientras chateo.",
"me he mojado por alguna situación ,estando en un lugar público .",
"he mentido sobre alguien para quedar bien yo.",
"he preferido a mi pareja antes de mis amistades.",
"he fantaseado con hacer una orgía ",
"me he imaginado soñando con un famoso.",
"he pasado una pena en el acto sexual.",
"me he mojado solo con un beso.",
"he jugado al yo nunca",
"he fingido estar borracho.",
"he mentido para ligar.",
"me he masturbado en una casa q no es la mía.",
"me he sentido atraída por alguno de los presentes.",
"he fantaseado con alguien mayor q yo.",
"me he levantado mojada.",
"he tenido un gatillazo haciendo el amor",
" he besado a una persona de mi mismo sexo",
"yo nunca he tenido ganas de acostarme con una amiga o amigo de mi novio o novia",
"He carecido de deseo sexual",
"He sido visto en el baño defencando",
"He mentido para encajar en un grupo",
"Le he contado algo a alguien y luego me he arrepentido",



]; 
	let l = textos.length





	function aleatorio(){
  		document.getElementById("resultado").innerHTML = "";
  		if (textos.length > 0) {
nro = Math.floor(Math.random() * (textos.length - 0) + 0);
     	document.getElementById("resultado").innerHTML = textos[nro];
//delete this index from the array so that it does not repeat
     	textos.splice(nro, 1);
	} else {	

    	document.getElementById("resultado").innerHTML = "Se acabo 😥, puede contribuir con mas preguntas enviando un correo a rop010698@gmail.com <br><br> <a class='ws' href='https://api.whatsapp.com/send?phone=+59896483278&text=Hola!%20Quiero%20cooperar%20con%20YoNunca!'>Contacte al desarrollador si desea cooperar</a>";
	}

document.getElementById("conteo").innerHTML = "";
document.getElementById("conteo").innerHTML = i + "/" + l;
i++

}


